production-settings:
  user-workflow:
    workflow-name: x402-payment-workflow-production
  workflow-artifacts:
    config-path: ./config.production.json
    secrets-path: ""
    workflow-path: ./wasm/workflow.wasm
staging-settings:
  user-workflow:
    workflow-name: x402-payment-workflow-staging
  workflow-artifacts:
    config-path: ./config.staging.json
    secrets-path: ""
    workflow-path: ./wasm/workflow.wasm
